name: flutter_shopping_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  dio: ^5.1.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
